# Generated by Django 5.2.1 on 2025-08-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
