# Generated by Django 5.2.1 on 2025-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentutilisateur',
            name='agence_adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='documentutilisateur',
            name='agence_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'agence/société"),
        ),
        migrations.AddField(
            model_name='documentutilisateur',
            name='representant_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone représentant légal'),
        ),
        migrations.AddField(
            model_name='documentutilisateur',
            name='structure_type',
            field=models.CharField(choices=[('particulier', 'Particulier / Individuel'), ('agence', 'Agence de location'), ('societe', 'Société')], default='particulier', max_length=50, verbose_name='Type de structure'),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='type_document',
            field=models.CharField(choices=[('carte_identite', "Carte d'identité"), ('permis_conduire', 'Permis de conduire'), ('passeport', 'Passeport'), ('attestation_travail', 'Attestation de travail'), ('justificatif_domicile', 'Justificatif de domicile'), ('rccm', 'Document RCCM'), ('autre', 'Autre document')], max_length=50, verbose_name='Type de document'),
        ),
    ]
