# Generated by Django 5.2.1 on 2025-08-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0004_documentutilisateur_agence_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Demande Vendor',
                'verbose_name_plural': 'Demandes Vendor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Auths.documentutilisateur',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
