# Generated by Django 5.2.1 on 2025-09-11 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0005_demandevendor_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('is_vendor', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reservations_count', models.IntegerField(default=0)),
                ('favoris_count', models.IntegerField(default=0)),
                ('avis_count', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suppression de compte',
                'verbose_name_plural': 'Suppressions de compte',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
