# Generated by Django 5.2.1 on 2025-09-11 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0006_accountdeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletionlog',
            name='hard_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountdeletionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
