# Generated by Django 5.2.1 on 2025-09-16 14:23

import Auths.models
import Auths.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0007_accountdeletionlog_hard_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentutilisateur',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=Auths.utils.document_upload_to, validators=[Auths.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Auths.utils.document_upload_to, validators=[Auths.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
