# Generated by Django 5.2.1 on 2025-09-26 01:32

import Auths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0008_alter_documentutilisateur_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentutilisateur',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=Auths.utils.document_upload_to, verbose_name='Fichier document'),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Auths.utils.document_upload_to, verbose_name='Image du document'),
        ),
    ]
