# Generated by Django 5.2.1 on 2025-07-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0023_alter_media_bien_alter_tarif_bien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Supabase')),
                ('property_name', models.CharField(max_length=255, verbose_name='Nom du bien')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('closed', 'Fermé'), ('archived', 'Archivé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Dernier message')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_host', to=settings.AUTH_USER_MODEL, verbose_name='Hôte')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='reservation.reservation', verbose_name='Réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Salon de chat',
                'verbose_name_plural': 'Salons de chat',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('file', 'Fichier'), ('system', 'Système')], default='text', max_length=20, verbose_name='Type de message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Salon de chat')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['created_at'],
            },
        ),
    ]
