# Generated by Django 5.2.1 on 2025-11-07 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message du signalement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('handled', models.BooleanField(default=False, verbose_name='Traité')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='chat.chatroom', verbose_name='Salon de chat')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_chat_reports', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant signalé')),
            ],
            options={
                'verbose_name': 'Signalement de chat',
                'verbose_name_plural': 'Signalements de chat',
                'ordering': ['-created_at'],
            },
        ),
    ]
