# Generated by Django 5.2.1 on 2025-06-03 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message du client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='annonce_id',
            field=models.PositiveIntegerField(verbose_name="ID de l'annonce"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
