# Generated by Django 5.2.1 on 2025-06-17 18:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmée le'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message du client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('ville', models.CharField(default='Abidjan', max_length=100, verbose_name='Ville')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('noteGlobale', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('vues', models.PositiveIntegerField(default=0)),
                ('disponibility', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propriétaire_bien', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='reservation.type_bien')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='annonce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservation_Bien_ids', to='reservation.bien'),
        ),
        migrations.CreateModel(
            name='HistoriqueStatutReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], max_length=50)),
                ('nouveau_statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], max_length=50)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_statut', to='reservation.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens/')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='reservation.bien')),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_paiement', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CREDIT_CARD', 'Carte de crédit/débit'), ('PREPAID_CARD', 'Carte prépayée'), ('LIQUIDE', 'Liquide')], default='MOBILE_MONEY', max_length=20)),
                ('numero_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration', models.CharField(blank=True, max_length=6, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiement',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('effectue', 'Effectué'), ('echoue', 'Échoué')], default='en_attente', max_length=20, verbose_name='Statut du paiement')),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('type_operation', models.CharField(choices=[('reservation', 'Réservation confirmée'), ('en_attente', 'Paiement en attente'), ('frais', 'Frais de service'), ('retrait', 'Retrait')], max_length=50, verbose_name='Type d’opération')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModePaiement', to='reservation.mode')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservation.reservation')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('reservation', 'Réservation confirmée'), ('en_attente', 'Paiement en attente'), ('frais', 'Frais de service'), ('retrait', 'Retrait')], max_length=50, verbose_name='Type d’opération')),
                ('montant', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='reservation.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prix', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('type_tarif', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('BIMENSUEL', 'Bimensuel'), ('TRIMESTRIEL', 'Trimensuel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé  le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarifs_Biens_id', to='reservation.bien')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='reservation.bien', verbose_name='Bien')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bien')},
            },
        ),
    ]
