# Generated by Django 5.2.1 on 2025-06-07 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_type_bien_bien_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens/')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='reservation.bien')),
            ],
        ),
    ]
