# Generated by Django 5.2.1 on 2025-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_tarif_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_tarif',
            field=models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('BIMENSUEL', 'Bimensuel'), ('TRIMESTRIEL', 'Trimensuel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], default='JOURNALIER', max_length=50, verbose_name='Type de tarif'),
        ),
    ]
