# Generated by Django 5.2.1 on 2025-06-27 15:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_bien_est_verifie_bien_has_piscine_bien_marque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5 étoiles)')),
                ('commentaire', models.TextField(max_length=1000, verbose_name='Commentaire')),
                ('note_proprete', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Propreté')),
                ('note_communication', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Communication')),
                ('note_emplacement', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Emplacement')),
                ('note_rapport_qualite_prix', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rapport qualité/prix')),
                ('recommande', models.BooleanField(default=True, verbose_name='Recommande ce bien')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Avis validé')),
                ('reponse_proprietaire', models.TextField(blank=True, max_length=500, null=True, verbose_name='Réponse du propriétaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservation.bien', verbose_name='Bien')),
                ('reservation', models.ForeignKey(help_text="L'avis est lié à une réservation spécifique", on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservation.reservation', verbose_name='Réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'reservation')},
            },
        ),
    ]
