# Generated by Django 5.2.1 on 2025-06-28 01:02

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_bien_est_verifie_bien_has_piscine_bien_marque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 28, 1, 2, 15, 34964, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='favori',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='historiquestatutreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 28, 1, 2, 21, 902543, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiquestatutreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 28, 1, 2, 29, 630434, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historiquepaiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(unique=True)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('0.5'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reservations', models.ManyToManyField(blank=True, help_text='Réservations qui ont utilisé ce code promo', related_name='codes_promos', to='reservation.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteHebdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.JSONField(default=list, help_text="Ex: ['lundi', 'mardi', 'jeudi']")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilite_hebdo', to='reservation.bien')),
            ],
            options={
                'verbose_name': 'Disponibilité Hebdomadaire',
                'verbose_name_plural': 'Disponibilités Hebdomadaires',
            },
        ),
    ]
