# Generated by Django 5.2.1 on 2025-07-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_document_created_at_document_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
        ),
        migrations.AddField(
            model_name='type_bien',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='types_bien', to='reservation.tagbien'),
        ),
    ]
