# Generated by Django 5.2.1 on 2025-07-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_merge_20250705_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation.bien'),
        ),
    ]
