# Generated by Django 5.2.1 on 2025-07-05 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_reservation_bien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents_biens/images/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents_biens/'),
        ),
        migrations.CreateModel(
            name='RevenuProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant brut (prix total)')),
                ('commission_plateforme', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission plateforme (15%)')),
                ('revenu_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Revenu net propriétaire (85%)')),
                ('status_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('verse', 'Versé'), ('bloque', 'Bloqué')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenus_proprietaire', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenu_proprietaire', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'Revenu Propriétaire',
                'verbose_name_plural': 'Revenus Propriétaires',
            },
        ),
    ]
