# Generated by Django 5.2.1 on 2025-07-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_document_image_alter_document_fichier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('type_facture', models.CharField(choices=[('reservation', 'Facture de réservation'), ('commission', 'Facture de commission'), ('avoir', 'Avoir (remboursement)')], default='reservation', max_length=20)),
                ('client_nom', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('client_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client')),
                ('client_adresse', models.TextField(blank=True, verbose_name='Adresse du client')),
                ('hote_nom', models.CharField(max_length=255, verbose_name="Nom de l'hôte")),
                ('hote_email', models.EmailField(max_length=254, verbose_name="Email de l'hôte")),
                ('hote_telephone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone de l'hôte")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('commission_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission plateforme')),
                ('montant_net_hote', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant net hôte')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='reservation.paiement')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
