# Generated by Django 5.2.1 on 2025-07-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_paiement_statut_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuproprietaire',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenu_proprietaire_record', to='reservation.reservation'),
        ),
    ]
