# Generated by Django 5.2.1 on 2025-07-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_alter_revenuproprietaire_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_tva',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='tva_taux',
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total'),
            preserve_default=False,
        ),
    ]
