# Generated by Django 5.2.1 on 2025-07-18 21:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_bien_chauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='carburant',
            field=models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], max_length=20, null=True, verbose_name='Type de carburant'),
        ),
        migrations.AddField(
            model_name='bien',
            name='prix_chauffeur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix supplémentaire pour le service de chauffeur', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix du chauffeur'),
        ),
        migrations.AddField(
            model_name='bien',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique'), ('semi_automatique', 'Semi-automatique')], max_length=20, null=True, verbose_name='Type de transmission'),
        ),
    ]
