# Generated by Django 5.2.1 on 2025-07-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_bien_tags_alter_tarif_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='reservation.bien'),
        ),
    ]
