# Generated by Django 5.2.1 on 2025-07-24 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_alter_tarif_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='disponibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='noteGlobale',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
