# Generated by Django 5.2.1 on 2025-07-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_alter_bien_disponibility_alter_bien_noteglobale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='carburant',
            field=models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('électrique', 'Électrique'), ('hybride', 'Hybride')], max_length=20, null=True, verbose_name='Type de carburant'),
        ),
    ]
