# Generated by Django 5.0.1 on 2025-08-02 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0027_alter_bien_carburant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='avis',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text="L'avis est lié à une réservation spécifique", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservation.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarifs_Biens_id', to='reservation.bien'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation__isnull', False)), fields=('user', 'reservation'), name='unique_avis_par_reservation'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation__isnull', True)), fields=('user', 'bien'), name='unique_avis_sans_reservation'),
        ),
    ]
