# Generated by Django 5.2.1 on 2025-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0028_alter_avis_unique_together_alter_avis_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilitehebdo',
            name='horaire_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='disponibilitehebdo',
            name='horaire_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
    ]
