# Generated by Django 5.2.1 on 2025-08-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0029_disponibilitehebdo_horaire_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type_media',
            field=models.CharField(choices=[('principale', 'Image principale'), ('galerie', 'Image de galerie'), ('carte_grise', 'Carte grise'), ('document', 'Document')], default='galerie', max_length=20, verbose_name='Type de média'),
        ),
    ]
