# Generated by Django 5.2.1 on 2025-08-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0030_media_type_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilitehebdo',
            name='horaire_debut',
            field=models.TimeField(default='09:00:00', verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='disponibilitehebdo',
            name='horaire_fin',
            field=models.TimeField(default='17:00:00', verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type_media',
            field=models.CharField(choices=[('galerie', 'Galerie'), ('video', 'Vidéo'), ('document', 'Document'), ('principale', 'Image principale')], default='galerie', max_length=50),
        ),
    ]
