# Generated by Django 5.0.1 on 2025-08-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0031_alter_disponibilitehebdo_horaire_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilitehebdo',
            old_name='horaire_debut',
            new_name='heure_debut',
        ),
        migrations.RenameField(
            model_name='disponibilitehebdo',
            old_name='horaire_fin',
            new_name='heure_fin',
        ),
        migrations.AddField(
            model_name='bien',
            name='has_garden',
            field=models.BooleanField(blank=True, null=True, verbose_name='Jardin'),
        ),
        migrations.AddField(
            model_name='bien',
            name='has_kitchen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cuisine équipée'),
        ),
        migrations.AddField(
            model_name='bien',
            name='has_parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='bien',
            name='has_security',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sécurité'),
        ),
        migrations.AddField(
            model_name='bien',
            name='has_wifi',
            field=models.BooleanField(blank=True, null=True, verbose_name='WiFi'),
        ),
        migrations.AddField(
            model_name='bien',
            name='lieu',
            field=models.CharField(blank=True, help_text='Localisation précise du bien (ex: Cocody, Deux-Plateaux)', max_length=255, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='bien',
            name='nb_douches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de salles de bain'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='has_piscine',
            field=models.BooleanField(blank=True, null=True, verbose_name='Piscine'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='nb_chambres',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type_media',
            field=models.CharField(choices=[('galerie', 'Galerie'), ('principale', 'Image principale'), ('document', 'Document (carte grise, etc.)')], default='galerie', max_length=20, verbose_name='Type de média'),
        ),
    ]
