# Generated by Django 5.2.1 on 2025-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0002_customuser_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.TextField(null=True),
        ),
    ]
