# Generated by Django 5.2.1 on 2025-06-22 23:23

import Auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0003_alter_customuser_birthdate_alter_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carte_identite',
            field=models.FileField(blank=True, null=True, upload_to=Auths.models.upload_path_cni),
        ),
        migrations.AddField(
            model_name='customuser',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permis_conduire',
            field=models.FileField(blank=True, null=True, upload_to=Auths.models.upload_path_permis),
        ),
    ]
