# Generated by Django 5.2.1 on 2025-07-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0005_customuser_otp_code_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_banniere',
            field=models.ImageField(blank=True, null=True, upload_to='bannieres/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
