# Generated by Django 5.2.1 on 2025-07-05 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0005_customuser_otp_code_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('type_document', models.CharField(choices=[('carte_identite', "Carte d'identité"), ('permis_conduire', 'Permis de conduire'), ('passeport', 'Passeport'), ('attestation_travail', 'Attestation de travail'), ('justificatif_domicile', 'Justificatif de domicile'), ('autre', 'Autre document')], max_length=50, verbose_name='Type de document')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents_utilisateurs/fichiers/', verbose_name='Fichier document')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents_utilisateurs/images/', verbose_name='Image du document')),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='en_attente', max_length=20, verbose_name='Statut de vérification')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('commentaire_moderateur', models.TextField(blank=True, null=True, verbose_name='Commentaire du modérateur')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_moderes', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document utilisateur',
                'verbose_name_plural': 'Documents utilisateur',
                'unique_together': {('utilisateur', 'type_document')},
            },
        ),
    ]
