# Generated by Django 5.2.1 on 2025-07-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0006_customuser_image_banniere_customuser_photo_profil'),
        ('Auths', '0006_documentutilisateur'),
    ]

    operations = [
    ]
