# Generated by Django 5.2.1 on 2025-07-15 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0009_parrainage_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_parrainage',
            field=models.CharField(blank=True, help_text="Code unique pour parrainer d'autres utilisateurs", max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nb_parrainages',
            field=models.IntegerField(default=0, verbose_name='Nombre de parrainages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parrain',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a parrainé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recompense_parrainage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Récompense de parrainage'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_parrainage',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle cet utilisateur a été parrainé', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parrainage_actif',
            field=models.BooleanField(default=True, help_text='Indique si le parrainage est encore actif'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points_parrainage',
            field=models.PositiveIntegerField(default=0, help_text='Points accumulés grâce au parrainage'),
        ),
    ]
