# Generated by Django 5.2.1 on 2025-08-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0011_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
