# Generated by Django 5.2.1 on 2025-06-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_type_bien_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='prix',
        ),
    ]
