# Generated by Django 5.2.1 on 2025-06-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_bien_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='nom',
        ),
    ]
