# Generated by Django 5.2.1 on 2025-06-26 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_type_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='has_piscine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='nb_chambres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='nb_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='plaque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents_biens/')),
                ('type', models.CharField(choices=[('carte_grise', 'Carte Grise'), ('assurance', 'Assurance'), ('attestation_propriete', 'Attestation de propriété'), ('autre', 'Autre')], max_length=100)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reservation.bien')),
            ],
        ),
    ]
