# Generated by Django 5.2.1 on 2025-07-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='cinetpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='payment_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historiquepaiement',
            name='type_operation',
            field=models.CharField(choices=[('reservation', 'Réservation'), ('remboursement', 'Remboursement'), ('commission', 'Commission'), ('en_attente', 'En attente'), ('initialisation', 'Initialisation'), ('annulation', 'Annulation')], max_length=50, verbose_name='Type d’opération'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModePaiement', to='reservation.mode'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_operation',
            field=models.CharField(choices=[('reservation', 'Réservation'), ('remboursement', 'Remboursement'), ('commission', 'Commission'), ('en_attente', 'En attente'), ('initialisation', 'Initialisation'), ('annulation', 'Annulation')], max_length=50, verbose_name="Type d'opération"),
        ),
        migrations.AlterModelTable(
            name='paiement',
            table='reservation_paiement',
        ),
    ]
