# Generated by Django 5.2.1 on 2025-07-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_avis'),
        ('reservation', '0008_tagbien_type_bien_tags'),
    ]

    operations = [
    ]
