# Generated by Django 5.2.1 on 2025-07-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_paiement_options_and_more'),
        ('reservation', '0008_rename_annonce_id_to_bien'),
    ]

    operations = [
    ]
