# Generated by Django 5.2.1 on 2025-07-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_merge_0007_avis_0008_tagbien_type_bien_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='biens', to='reservation.tagbien'),
        ),
    ]
