# Generated by Django 5.2.1 on 2025-07-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(choices=[('pending', 'En attente'), ('effectue', 'Effectué'), ('echec', 'Échoué'), ('rembourse', 'Remboursé')], default='pending', max_length=20),
        ),
    ]
