# Generated by Django 5.2.1 on 2025-07-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_bien_tags'),
        ('reservation', '0015_remove_facture_montant_ht_remove_facture_montant_ttc_and_more'),
    ]

    operations = [
    ]
