# Generated by Django 5.2.1 on 2025-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_merge_20250707_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_total',
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant HT'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TTC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='tva_taux',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
