# Generated by Django 5.2.1 on 2025-07-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_remove_bien_tags_remove_facture_montant_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagbien',
            name='iconName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
