# Generated by Django 5.2.1 on 2025-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_tagbien_iconname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='chauffeur',
            field=models.BooleanField(default=False, help_text='Indique si un chauffeur est inclus avec le bien', verbose_name='Chauffeur inclus'),
        ),
    ]
