# Generated by Django 5.2.1 on 2025-07-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0021_ville_remove_bien_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='reservation.ville', verbose_name='Ville'),
        ),
    ]
