# Generated by Django 5.2.1 on 2025-07-19 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_bien_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reservation.bien'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='reservation.bien'),
        ),
    ]
