# Generated by Django 5.2.1 on 2025-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_alter_media_bien_alter_tarif_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
    ]
