# Generated by Django 5.2.1 on 2025-07-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_alter_media_bien_alter_tarif_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='biens', to='reservation.tagbien'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarifs_Biens_id', to='reservation.bien'),
        ),
    ]
