# Generated by Django 5.2.1 on 2025-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_alter_tarif_created_at'),
        ('reservation', '0025_alter_tarif_bien'),
    ]

    operations = [
    ]
