# Generated by Django 5.2.1 on 2025-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_merge_20250724_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquepaiement',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='historiquepaiement',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='HistoriquePaiement',
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
