# Generated by Django 5.2.1 on 2025-09-03 19:07

import Auths.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0027_remove_historiquepaiement_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Auths.utils.bien_image_upload_to)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservation.bien')),
            ],
        ),
    ]
